# - Find gpstk library
# Find the native gpstk includes and library
# This module defines
#  GPSTK_INCLUDE_DIR, where to find tiff.h, etc.
#  GPSTK_LIBRARIES, libraries to link against to use GPSTK.
#  GPSTK_FOUND, If false, do not try to use GPSTK.
# also defined, but not for general use are
#  GPSTK_LIBRARY, where to find the GPSTK library.

SET(GPSTK_ROOT_CANDIDATES "")

IF(GPSTK_ROOT)
  LIST(APPEND GPSTK_ROOT_CANDIDATES ${GPSTK_ROOT})
ENDIF()

IF(DEFINED ENV{GPSTK_ROOT})
  LIST(APPEND GPSTK_ROOT_CANDIDATES $ENV{GPSTK_ROOT})
ENDIF()

IF(OSSIM_DEV_HOME)
  LIST(APPEND GPSTK_ROOT_CANDIDATES ${OSSIM_DEV_HOME}/3rdparty/gpstk)
ENDIF()

IF(CMAKE_INSTALL_PREFIX)
  LIST(APPEND GPSTK_ROOT_CANDIDATES ${CMAKE_INSTALL_PREFIX})
ENDIF()

IF(OSSIM_INSTALL_PREFIX)
  LIST(APPEND GPSTK_ROOT_CANDIDATES ${OSSIM_INSTALL_PREFIX})
ENDIF()

LIST(APPEND GPSTK_ROOT_CANDIDATES
  /opt/homebrew
  /usr/local
  /usr
)

FIND_PATH(GPSTK_INCLUDE_DIR
  NAMES gpstk/Matrix.hpp
  PATHS ${GPSTK_ROOT_CANDIDATES}
  PATH_SUFFIXES include
)

SET(GPSTK_NAMES ${GPSTK_NAMES} gpstk libgpstk)
FIND_LIBRARY(GPSTK_LIBRARY
  NAMES ${GPSTK_NAMES}
  PATHS ${GPSTK_ROOT_CANDIDATES}
  PATH_SUFFIXES lib lib64
)

# handle the QUIETLY and REQUIRED arguments and set GPSTK_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GPSTK  DEFAULT_MSG  GPSTK_LIBRARY  GPSTK_INCLUDE_DIR)

IF(GPSTK_FOUND)
  SET( GPSTK_LIBRARIES ${GPSTK_LIBRARY} )
ENDIF(GPSTK_FOUND)

MARK_AS_ADVANCED(GPSTK_INCLUDE_DIR GPSTK_LIBRARY)
