//----------------------------------------------------------------------------
//
// License:  MIT
//
// See LICENSE.txt file in the top level directory for more details.
//
// Author:  Ryan Feldbush
//
// Description: CSSFAB des class definition.
//
// Exploitation Reference Data TRE.
//
// See document App AH - GLAS-GFM table AH.6.6 for more info.
//
//----------------------------------------------------------------------------

#include <ossim/support_data/ossimNitfCssfabDes.h>

ossimNitfCssfabDes::ossimNitfCssfabDes(ossim_uint32 desLength)
   : ossimNitfGenericDes("CSSFAB", desLength)
{
   FIELD_DEFINITIONS =
      {
   //{"DE", 2},
   //{"DESID", 25},
   {"DESVER", 2, {1}},
   {"DESCLAS to DESCTLN", 167},
   {"DESSHL", 4, {1}},
   {"UUID", 36},
   {"NUMAIS", 3, {1}},
   {"NUMAIS n", LOOP_START},
      {"AISDLVL", 3, {1}},
   {"NUMAIS n", LOOP_END},
   {"NUM_ASSOC_ELEM", 3, {1}},
   {"NUM_ASSOC_ELEM n", LOOP_START},
      {"ASSOC_ELEM_UUID", 36},
   {"NUM_ASSOC_ELEM n", LOOP_END},
   {"RESERVEDSUBH_LEN", 4},///Empty?
   {"RESERVEDSUBH RESERVEDSUBH_LEN", VARIABLE_LENGTH},///Empty?
   {"SENSOR_TYPE", 1},
   {"BAND_TYPE", 1},
   {"BAND_WAVELENGTH", 11, {3, 8}},
   {"N_BANDS", 5, {1}},
   {"N_BANDS i", LOOP_START},
      {"BAND_INDEX", 5, {1}},
      {"IREPBAND", 2},
      {"ISUBCAT", 6},
   {"N_BANDS i", LOOP_END},
   {"NUM_FL_PTS", 3, {1}},
   {"FL_INTERP", 1},
   {"FOC_LENGTH_DATE", 8},
   {"NUM_FL_PTS n", LOOP_START},
      {"FOC_LENGTH_TIME", 15, {3, 9}},
      {"FOC_LENGTH", 11, {3, 8}},
   {"NUM_FL_PTS n", LOOP_END},
   {"PPOFF_X", 10, {4, 6}},
   {"PPOFF_Y", 10, {4, 6}},
   {"PPOFF_Z", 10, {4, 7}},
   {"ANGOFF_X", 10, {4, 7}},
   {"ANGOFF_Y", 10, {4, 7}},
   {"ANGOFF_Z", 10, {4, 7}},
   {"SENSOR_TYPE == S", IF_STATEMENT_START},
      {"SMPL_NUM_FIRST", 12, {4, 5}},
      {"DELTA_SMPL_PAIRS", 11, {3, 5}},
      {"NUM_FA_PAIRS", 3, {1}},
      {"NUM_FA_PAIRS n", LOOP_START},
         {"START_FALIGN_X", 11, {4, 7}},
         {"START_FALIGN_Y", 11, {4, 7}},
         {"END_FALIGN_X", 11, {4, 7}},
         {"END_FALIGN_Y", 11, {4, 7}},
      {"NUM_FA_PAIRS n", LOOP_END},
   {"SENSOR_TYPE == S", IF_STATEMENT_END},
   {"SENSOR_TYPE == F", IF_STATEMENT_START},
      {"NUM_SETS_FA_DATA", 1},
      {"FIELD_ANGLE_TYPE", 1},
      {"FA_INTERP", 1},
      {"FIELD_ANGLE_TYPE == 0", IF_STATEMENT_START},
         {"NUM_SETS_FA_DATA n", LOOP_START},
            {"FL_CAL", 11, {3, 8}},
            {"NUM_FIR_LINE", 12, {4, 5}},
            {"DELTA_LINE", 11, {3, 5}},
            {"NUM_FA_BLOCKS_LINE", 3, {1}},
            {"NUM_FIR_SAMP", 12, {4, 5}},
            {"DELTA_SAMP", 11, {4, 5}},
            {"NUM_FA_BLOCKS_SAMP", 3, {1}},
            {"NUM_FA_BLOCKS_LINE i", LOOP_START},
               {"NUM_FA_BLOCKS_SAMP j", LOOP_START},
                  {"FA_X1", 11, {4, 7}},
                  {"FA_Y1", 11, {4, 7}},
                  {"FA_X2", 11, {4, 7}},
                  {"FA_Y2", 11, {4, 7}},
                  {"FA_X3", 11, {4, 7}},
                  {"FA_Y3", 11, {4, 7}},
                  {"FA_X4", 11, {4, 7}},
                  {"FA_Y4", 11, {4, 7}},
               {"NUM_FA_BLOCKS_SAMP j", LOOP_END},
            {"NUM_FA_BLOCKS_LINE i", LOOP_END},
         {"NUM_SETS_FA_DATA n", LOOP_END},
      {"FIELD_ANGLE_TYPE == 0", IF_STATEMENT_END},
      {"FIELD_ANGLE_TYPE == 1", IF_STATEMENT_START},
         {"NUM_FP_ARRAYS_LINE", 3, {1}},
         {"NUM_FP_ARRAYS_SAMP", 3, {1}},
         {"NUM_FP_ARRAYS_LINE n", LOOP_START},
            {"NUM_FP_ARRAYS_SAMP j", LOOP_START},
            {"LS_FID_TRANS_T0", 21, {5}},
            {"LS_FID_TRANS_T1", 21, {5}},
            {"LS_FID_TRANS_T2", 21, {5}},
            {"LS_FID_TRANS_T3", 21, {5}},
            {"LS_FID_TRANS_T4", 21, {5}},
            {"LS_FID_TRANS_T5", 21, {5}},
            {"LS_FID_TRANS_T6", 21, {5}},
            {"LS_FID_TRANS_T7", 21, {5}},
            {"NUM_FP_ARRAYS_LINE n", LOOP_END},
         {"NUM_FP_ARRAYS_SAMP j", LOOP_END},
         {"NUM_SETS_FA_DATA n", LOOP_START},
            {"FL_CAL_IOP", 11, {3, 8}},
            {"PPO_X0", 21, {5}},
            {"PPO_Y0", 21, {5}},
            {"RLD_K0", 21, {5}},
            {"RLD_K1", 21, {5}},
            {"RLD_K2", 21, {5}},
            {"RLD_K3", 21, {5}},
            {"DCD_P1", 21, {5}},
            {"DCD_P2", 21, {5}},
            {"DCD_P3", 21, {5}},
            {"AD_A1", 21, {5}},
            {"AD_A2", 21, {5}},
            {"RADIUS_OF_VALIDITY", 21, {5}},
         {"NUM_SETS_FA_DATA n", LOOP_END},
      {"FIELD_ANGLE_TYPE == 1", IF_STATEMENT_END},
      {"TELESCOPE_OPTICS_FLAG", 1},
      {"TELESCOPE_OPTICS_FLAG == 1", IF_STATEMENT_START},
         {"NUM_TELE_SETS_FA_DATA", 1},
         {"N_FRAMES", 4, {1}},
         {"N_FRAMES n", LOOP_START},
            {"TELE_TRANS_T0", 21, {5}},
            {"TELE_TRANS_T1", 21, {5}},
            {"TELE_TRANS_T2", 21, {5}},
            {"TELE_TRANS_T3", 21, {5}},
            {"TELE_TRANS_T4", 21, {5}},
            {"TELE_TRANS_T5", 21, {5}},
            {"TELE_TRANS_T6", 21, {5}},
            {"TELE_TRANS_T7", 21, {5}},
         {"N_FRAMES n", LOOP_END},
         {"NUM_TELE_SETS_FA_DATA n", LOOP_START},
            {"FL_CAL_IOP_TELE", 11, {3, 8}},
            {"PPO_X0_TELE", 21, {5}},
            {"PPO_Y0_TELE", 21, {5}},
            {"RLD_K0_TELE", 21, {5}},
            {"RLD_K1_TELE", 21, {5}},
            {"RLD_K2_TELE", 21, {5}},
            {"RLD_K3_TELE", 21, {5}},
            {"DCD_P1_TELE", 21, {5}},
            {"DCD_P2_TELE", 21, {5}},
            {"DCD_P3_TELE", 21, {5}},
            {"AD_A1_TELE", 21, {5}},
            {"AD_A2_TELE", 21, {5}},
            {"RADIUS_OF_VALIDITY_TELE", 21, {5}},
         {"NUM_TELE_SETS_FA_DATA n", LOOP_END},
      {"TELESCOPE_OPTICS_FLAG == 1", IF_STATEMENT_END},
      {"TELESCOPE_OPTICS_FLAG == 2", IF_STATEMENT_START},
         {"NUM_TELE_SETS_FA_DATA", 1},
         {"N_FRAME_TIMES", 4, {1}},
         {"N_VARYING_IO", 2, {1}},
         {"N_VARYING_IO n", LOOP_START},
            {"TIME_VARYING_IO_PARM_ID", 2, {1}}, //
         {"N_VARYING_IO n", LOOP_END},
         {"TELE_DATE", 8},
         {"N_FRAME_TIMES n", LOOP_START},
            {"TELE_TIME", 15, {3, 9}}, //
            {"TELE_TRANS_T0", 21, {5}},
            {"TELE_TRANS_T1", 21, {5}},
            {"TELE_TRANS_T2", 21, {5}},
            {"TELE_TRANS_T3", 21, {5}},
            {"TELE_TRANS_T4", 21, {5}},
            {"TELE_TRANS_T5", 21, {5}},
            {"TELE_TRANS_T6", 21, {5}},
            {"TELE_TRANS_T7", 21, {5}},
            {"N_VARYING_IO m", LOOP_START},
               {"TIME_VARYING_IO_M", 21, {5}},
            {"N_VARYING_IO m", LOOP_END},
         {"N_FRAME_TIMES n", LOOP_END},
         {"NUM_TELE_SETS_FA_DATA", LOOP_START},
            {"FL_CAL_IOP_TELE", 11, {3, 8}},
            {"PPO_X0_TELE", 21, {5}},
            {"PPO_Y0_TELE", 21, {5}},
            {"RLD_K0_TELE", 21, {5}},
            {"RLD_K1_TELE", 21, {5}},
            {"RLD_K2_TELE", 21, {5}},
            {"RLD_K3_TELE", 21, {5}},
            {"DCD_P1_TELE", 21, {5}},
            {"DCD_P2_TELE", 21, {5}},
            {"DCD_P3_TELE", 21, {5}},
            {"AD_A1_TELE", 21, {5}},
            {"AD_A2_TELE", 21, {5}},
            {"RADIUS_OF_VALIDITY_TELE", 21, {5}},
         {"NUM_TELE_SETS_FA_DATA", LOOP_END},
      {"TELESCOPE_OPTICS_FLAG == 2", IF_STATEMENT_END},
   {"SENSOR_TYPE == F", IF_STATEMENT_END},
   {"RESERVED_LEN", 9, {1}}
      };
}