//----------------------------------------------------------------------------
//
// License:  MIT
//
// See LICENSE.txt file in the top level directory for more details.
//
// Author:  Ryan Feldbush
//
// Description: CSCSDB des class definition.
//
// Exploitation Reference Data TRE.
//
// See document App AH - GLAS-GFM table AH.6.6 for more info.
//
//----------------------------------------------------------------------------

#include <ossim/support_data/ossimNitfCscsdbDes.h>
#include <ossim/base/ossimNotify.h>
#include <ossim/base/ossimTrace.h>
#include <ossim/support_data/ossimNitfCommonFieldNames.h>

static ossimTrace traceDebug("ossimNitfCscsdbdes:debug");

const std::string ossimNitfCscsdbDes::CETAG_KW = "CSCSDB";

ossimNitfCscsdbDes::ossimNitfCscsdbDes()
   : ossimNitfGenericDes("CSCSDB")
{
	initializeFieldDefinitions();
	initializeFields();
	setDesSubHeaderLength(getDesSubHeaderLength());
	setDesDataLength(getDesDataLength());
}

ossimNitfCscsdbDes::ossimNitfCscsdbDes(ossim_uint32 tagLength)
   : ossimNitfGenericDes("CSCSDB", tagLength)
{
	initializeFieldDefinitions();
	initializeFields();
	setDesSubHeaderLength(getDesSubHeaderLength());
}
void ossimNitfCscsdbDes::initializeFieldDefinitions()
{
   FIELD_DEFINITIONS =
   {
        {ossim::nitf::UUID_KW, 36, 0, 0, " "},
        {ossim::nitf::NUMAIS_KW, 3, 0, 0, "ALL"},
        {ossim::nitf::NUMAIS_KW, LOOP_START},
            {ossim::nitf::AISDLVL_KW, 3, 1},
        {ossim::nitf::NUMAIS_KW, LOOP_END},
        {ossim::nitf::NUM_ASSOC_ELEM_KW, 3, 1, 0, "1"},
        {ossim::nitf::NUM_ASSOC_ELEM_KW, LOOP_START},
            {ossim::nitf::ASSOC_ELEM_UUID_KW, 36, 0},
        {ossim::nitf::NUM_ASSOC_ELEM_KW, LOOP_END},
        {ossim::nitf::RESERVEDSUBH_LEN_KW, 4, 1},
        {ossim::nitf::RESERVEDSUBH_KW + " " + ossim::nitf::RESERVEDSUBH_LEN_KW, VARIABLE_LENGTH, 1},
        {ossim::nitf::COV_VERSION_DATE_KW, 8, U_INT, 0, "20240501"},
        {ossim::nitf::CORE_SETS_KW, 1, U_INT, 0, "1"},
        {ossim::nitf::CORE_SETS_KW, LOOP_START},
            {ossim::nitf::REF_FRAME_POSITION_KW, 1, U_INT, 0, "1"},
            {ossim::nitf::REF_FRAME_ATTITUDE_KW, 1, U_INT, 0, "2"},
            {ossim::nitf::NUM_GROUPS_KW, 1, U_INT, 0, "4"},
            {ossim::nitf::NUM_GROUPS_KW, LOOP_START},
                {ossim::nitf::CORR_REF_DATE_KW, 8, U_INT, 0, "20000101"},
                {ossim::nitf::CORR_REF_TIME_KW, 16, U_DOUBLE, 9},
                {ossim::nitf::NUM_ADJ_PARM_KW, 1, U_INT},
                {ossim::nitf::NUM_ADJ_PARM_KW, LOOP_START},
                    {ossim::nitf::ADJ_PARM_ID_KW, 1, U_INT},
                {ossim::nitf::NUM_ADJ_PARM_KW, LOOP_END},
                {ossim::nitf::BASIC_SUB_ALLOC_KW, 1, U_INT, 0, "1"},
                {ossim::nitf::BASIC_SUB_ALLOC_KW + " = 1", IF_STATEMENT_START},
                    {"( " + ossim::nitf::NUM_ADJ_PARM_KW + " * 0.5 ) * ( " + ossim::nitf::NUM_ADJ_PARM_KW + " + 1 )", LOOP_START},
                        {ossim::nitf::ERRCOV_C1_KW, 21, SCIENTIFIC, 0, "1.0e-16"},
                    {"( " + ossim::nitf::NUM_ADJ_PARM_KW + " * 0.5 ) * ( " + ossim::nitf::NUM_ADJ_PARM_KW + " + 1 )", LOOP_END},
                    {ossim::nitf::BASIC_PF_FLAG_KW, 1, U_INT},
                    {ossim::nitf::BASIC_PF_FLAG_KW + " = 1", IF_STATEMENT_START},
                        {ossim::nitf::NUM_BASIC_PF_KW, 2, U_INT},
                        {ossim::nitf::NUM_BASIC_PF_KW, LOOP_START},
                            {ossim::nitf::BASIC_PF_SPDCF_KW, 2, U_INT},
                            {ossim::nitf::NUM_PAIRINGS_BASIC_PF_KW, 2, U_INT},
                            {ossim::nitf::NUM_PAIRINGS_BASIC_PF_KW, LOOP_START},
                                {ossim::nitf::BASIC_PF_SPDCF_SENSOR_KW, 6, ASCII},
                            {ossim::nitf::NUM_PAIRINGS_BASIC_PF_KW, LOOP_END},
                        {ossim::nitf::NUM_BASIC_PF_KW, LOOP_END},
                    {ossim::nitf::BASIC_PF_FLAG_KW + " = 1", IF_STATEMENT_END},
                    {ossim::nitf::BASIC_PL_FLAG_KW, 1, U_INT},
                    {ossim::nitf::BASIC_PL_FLAG_KW + " = 1", IF_STATEMENT_START},
                        {ossim::nitf::NUM_BASIC_PL_KW, 2, U_INT},
                        {ossim::nitf::NUM_BASIC_PL_KW, LOOP_START},
                            {ossim::nitf::BASIC_PL_SPDCF_KW, 2, U_INT},
                            {ossim::nitf::NUM_PAIRINGS_BASIC_PL_KW, 2, U_INT},
                            {ossim::nitf::NUM_PAIRINGS_BASIC_PL_KW, LOOP_START},
                                {ossim::nitf::BASIC_PL_SPDCF_SENSOR_KW, 6, ASCII},
                            {ossim::nitf::NUM_PAIRINGS_BASIC_PL_KW, LOOP_END},
                        {ossim::nitf::NUM_BASIC_PL_KW, LOOP_END},
                    {ossim::nitf::BASIC_PL_FLAG_KW + " = 1", IF_STATEMENT_END},
                    {ossim::nitf::BASIC_SR_FLAG_KW, 1, U_INT, 0, "1"},
                    {ossim::nitf::BASIC_SR_FLAG_KW + " = 1", IF_STATEMENT_START},
                        {ossim::nitf::BASIC_SR_SPDCF_KW, 2, U_INT},
                    {ossim::nitf::BASIC_SR_FLAG_KW + " = 1", IF_STATEMENT_END},
                {ossim::nitf::BASIC_SUB_ALLOC_KW + " = 1", IF_STATEMENT_END},
                {ossim::nitf::POST_SUB_ALLOC_KW, 1, U_INT, 0, "1"},
                {ossim::nitf::POST_SUB_ALLOC_KW + " = 1", IF_STATEMENT_START},
                    {ossim::nitf::POST_START_DATE_KW, 8, U_INT},
                    {ossim::nitf::POST_START_TIME_KW, 15, U_DOUBLE, 9},
                    {ossim::nitf::POST_DT_KW, 13, U_DOUBLE, 9},
                    {ossim::nitf::NUM_POSTS_KW, 3, U_INT},
                    {ossim::nitf::COMMON_POSTS_COV_KW, 1, U_INT, 0, "1"},
                    {ossim::nitf::COMMON_POSTS_COV_KW + " = 1", IF_STATEMENT_START},
                        {"( " + ossim::nitf::NUM_ADJ_PARM_KW + " * 0.5 ) * ( " + ossim::nitf::NUM_ADJ_PARM_KW + " + 1 )", LOOP_START},
                            {ossim::nitf::ERRCOV_C2_KW, 21, SCIENTIFIC},
                        {"( " + ossim::nitf::NUM_ADJ_PARM_KW + " * 0.5 ) * ( " + ossim::nitf::NUM_ADJ_PARM_KW + " + 1 )", LOOP_END},
                    {ossim::nitf::COMMON_POSTS_COV_KW + " = 1", IF_STATEMENT_END},
                    {ossim::nitf::COMMON_POSTS_COV_KW + " = 0", IF_STATEMENT_START},
                        {ossim::nitf::NUM_POSTS_KW, LOOP_START},
                            {"( " + ossim::nitf::NUM_ADJ_PARM_KW + " * 0.5 ) * ( " + ossim::nitf::NUM_ADJ_PARM_KW + " + 1 )", LOOP_START},
                                {ossim::nitf::ERRCOV_C2_KW, 21, SCIENTIFIC},
                            {"( " + ossim::nitf::NUM_ADJ_PARM_KW + " * 0.5 ) * ( " + ossim::nitf::NUM_ADJ_PARM_KW + " + 1 )", LOOP_END},
                        {ossim::nitf::NUM_POSTS_KW, LOOP_END},
                    {ossim::nitf::COMMON_POSTS_COV_KW + " = 0", IF_STATEMENT_END},
                    {ossim::nitf::POST_INTERP_KW, 1, U_INT, 0, "1"},
                    {ossim::nitf::POST_PF_FLAG_KW, 1, U_INT},
                    {ossim::nitf::POST_PF_FLAG_KW + " = 1", IF_STATEMENT_START},
                        {ossim::nitf::NUM_POST_PF_KW, 2, U_INT},
                        {ossim::nitf::NUM_POST_PF_KW, LOOP_START},
                            {ossim::nitf::POST_PF_SPDCF_KW, 2, U_INT},
                            {ossim::nitf::NUM_PAIRINGS_POST_PF_KW, 2, U_INT},
                            {ossim::nitf::NUM_PAIRINGS_POST_PF_KW, LOOP_START},
                                {ossim::nitf::POST_PF_SPDCF_SENSOR_KW, 6, SCIENTIFIC},
                            {ossim::nitf::NUM_PAIRINGS_POST_PF_KW, LOOP_END},
                        {ossim::nitf::NUM_POST_PF_KW, LOOP_END},
                    {ossim::nitf::POST_PF_FLAG_KW + " = 1", IF_STATEMENT_END},
                    {ossim::nitf::POST_PL_FLAG_KW, 1, U_INT},
                    {ossim::nitf::POST_PL_FLAG_KW + " = 1", IF_STATEMENT_START},
                        {ossim::nitf::NUM_POST_PL_KW, 2, U_INT},
                        {ossim::nitf::NUM_POST_PL_KW, LOOP_START},
                            {ossim::nitf::POST_PL_SPDCF_KW, 2, U_INT},
                            {ossim::nitf::NUM_PAIRINGS_POST_PL_KW, 2, U_INT},
                            {ossim::nitf::NUM_PAIRINGS_POST_PL_KW, LOOP_START},
                                {ossim::nitf::POST_PL_SPDCF_SENSOR_KW, 6, ASCII},
                            {ossim::nitf::NUM_PAIRINGS_POST_PL_KW, LOOP_END},
                        {ossim::nitf::NUM_POST_PL_KW, LOOP_END},
                    {ossim::nitf::POST_PL_FLAG_KW + " = 1", IF_STATEMENT_END},
                    {ossim::nitf::POST_SR_FLAG_KW, 1, U_INT, 0, "1"},
                    {ossim::nitf::POST_SR_FLAG_KW + " = 1", IF_STATEMENT_START},
                        {ossim::nitf::POST_SR_SPDCF_KW, 2, U_INT},
                        {ossim::nitf::POST_CORR_KW, 1, U_INT},
                    {ossim::nitf::POST_SR_FLAG_KW + " = 1", IF_STATEMENT_END},
                {ossim::nitf::POST_SUB_ALLOC_KW + " = 1", IF_STATEMENT_END},
            {ossim::nitf::NUM_GROUPS_KW, LOOP_END},
        {ossim::nitf::CORE_SETS_KW, LOOP_END},
        {ossim::nitf::IO_CAL_AP_KW, 1, U_INT},
        {ossim::nitf::IO_CAL_AP_KW + " = 1", IF_STATEMENT_START},
            {ossim::nitf::NUM_SETS_CAL_AP_KW, 2, U_INT},
            {ossim::nitf::NUM_SETS_CAL_AP_KW, LOOP_START},
                {ossim::nitf::FOCAL_LENGTH_CAL_KW, 11, U_DOUBLE, 8},
            {ossim::nitf::NUM_SETS_CAL_AP_KW, LOOP_END},
            {ossim::nitf::NCAL_CPG_KW, 2, U_INT},
            {ossim::nitf::NCAL_CPG_KW, LOOP_START},
                {ossim::nitf::CORR_REF_DATE_IO_KW, 8, U_INT},
                {ossim::nitf::CORR_REF_TIME_IO_KW, 16, U_DOUBLE, 9},
                {ossim::nitf::N1CAL_KW, 2, U_INT},
                {ossim::nitf::N1CAL_KW, LOOP_START},
                    {ossim::nitf::CAL_AP_ID_KW, 2, U_INT},
                {ossim::nitf::N1CAL_KW, LOOP_END},
                {ossim::nitf::NUM_SETS_CAL_AP_KW, LOOP_START},
                    {"( " + ossim::nitf::N1CAL_KW + " * 0.5 ) * ( " + ossim::nitf::N1CAL_KW + " + 1 )", LOOP_START},
                        {ossim::nitf::ERRCOV_C3_KW, 21, SCIENTIFIC},
                    {"( " + ossim::nitf::N1CAL_KW + " * 0.5 ) * ( " + ossim::nitf::N1CAL_KW + " + 1 )", LOOP_END},
                {ossim::nitf::NUM_SETS_CAL_AP_KW, LOOP_END},
                {ossim::nitf::CAL_INTERP_KW, 1, U_INT},
                {ossim::nitf::SPDCF_ID_TIME_KW, 2, U_INT},
                {ossim::nitf::SPDCF_ID_FL_KW, 2, U_INT},
            {ossim::nitf::NCAL_CPG_KW, LOOP_END},
        {ossim::nitf::IO_CAL_AP_KW + " = 1", IF_STATEMENT_END},
        {ossim::nitf::TS_CAL_AP_KW, 1, U_INT},
        {ossim::nitf::TS_CAL_AP_KW + " = 1", IF_STATEMENT_START},
            {ossim::nitf::NUM_TS_GRP_KW, 1, U_INT},
            {ossim::nitf::NUM_TS_GRP_KW + " = 1", IF_STATEMENT_START},
                {ossim::nitf::CORR_REF_DATE_TS_KW, 8, U_INT},
                {ossim::nitf::CORR_REF_TIME_TS_KW, 16, U_DOUBLE, 9},
                {ossim::nitf::TSRR_KW, 21, SCIENTIFIC},
                {ossim::nitf::TSRC_KW, 21, SCIENTIFIC},
                {ossim::nitf::TSCC_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_SPDCF_KW, 2, U_INT},
            {ossim::nitf::NUM_TS_GRP_KW + " = 1", IF_STATEMENT_END},
            {ossim::nitf::NUM_TS_GRP_KW + " = 2", IF_STATEMENT_START},
                {ossim::nitf::CORR_REF_DATE_TSP_KW, 8, U_DOUBLE, 25},
                {ossim::nitf::CORR_REF_TIME_TSP_KW, 16, U_DOUBLE, 25},
                {ossim::nitf::TS_POS_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_POS_SPDCF_KW, 2, U_INT},
                {ossim::nitf::CORR_REF_DATE_TSA_KW, 8, U_DOUBLE, 25},
                {ossim::nitf::CORR_REF_TIME_TSA_KW, 16, U_DOUBLE, 25},
                {ossim::nitf::TS_ATT_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_ATT_SPDCF_KW, 2, U_INT},
            {ossim::nitf::NUM_TS_GRP_KW + " = 2", IF_STATEMENT_END},
            {ossim::nitf::NUM_TS_GRP_KW + " = 3", IF_STATEMENT_START},
                {ossim::nitf::CORR_REF_DATE_TS_KW, 8, U_DOUBLE, 25},
                {ossim::nitf::CORR_REF_TIME_TS_KW, 16, U_DOUBLE, 25},
                {ossim::nitf::TS_POS_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_POS_ATT_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_POS_FL_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_ATT_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_ATT_FL_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_FL_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_SPDCF_KW, 2, U_INT},
            {ossim::nitf::NUM_TS_GRP_KW + " = 3", IF_STATEMENT_END},
            {ossim::nitf::NUM_TS_GRP_KW + " = 4", IF_STATEMENT_START},
                {ossim::nitf::CORR_REF_DATE_TSPA_KW, 8, U_DOUBLE, 25},
                {ossim::nitf::CORR_REF_TIME_TSPA_KW, 16, U_DOUBLE, 25},
                {ossim::nitf::TS_POS_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_POS_ATT_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_ATT_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_PA_SPDCF_KW, 2, U_INT},
                {ossim::nitf::CORR_REF_DATE_TSFL_KW, 8, U_DOUBLE, 25},
                {ossim::nitf::CORR_REF_TIME_TSFL_KW, 16, U_DOUBLE, 25},
                {ossim::nitf::TS_FL_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_FL_SPDCF_KW, 2, U_INT},
            {ossim::nitf::NUM_TS_GRP_KW + " = 4", IF_STATEMENT_END},
            {ossim::nitf::NUM_TS_GRP_KW + " = 5", IF_STATEMENT_START},
                {ossim::nitf::CORR_REF_DATE_TSP_KW, 8, U_DOUBLE, 25},
                {ossim::nitf::CORR_REF_TIME_TSP_KW, 16, U_DOUBLE, 25},
                {ossim::nitf::TS_POS_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_POS_SPDCF_KW, 2, U_INT},
                {ossim::nitf::CORR_REF_DATE_TSA_KW, 8, U_DOUBLE, 25},
                {ossim::nitf::CORR_REF_TIME_TSA_KW, 16, U_DOUBLE, 25},
                {ossim::nitf::TS_ATT_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_ATT_SPDCF_KW, 2, U_INT},
                {ossim::nitf::CORR_REF_DATE_TSFL_KW, 8, U_DOUBLE, 25},
                {ossim::nitf::CORR_REF_TIME_TSFL_KW, 16, U_DOUBLE, 25},
                {ossim::nitf::TS_FL_COV_KW, 21, SCIENTIFIC},
                {ossim::nitf::TS_FL_SPDCF_KW, 2, U_INT},
            {ossim::nitf::NUM_TS_GRP_KW + " = 5", IF_STATEMENT_END},
        {ossim::nitf::TS_CAL_AP_KW + " = 1", IF_STATEMENT_END},
        {ossim::nitf::UE_FLAG_KW, 1, U_INT, 0, "1"},
        {ossim::nitf::UE_FLAG_KW + " = 1", IF_STATEMENT_START},
            {ossim::nitf::LINE_DIMENSION_KW, 3, U_INT},
            {ossim::nitf::SAMPLE_DIMENSION_KW, 2, U_INT},
            {ossim::nitf::LINE_DIMENSION_KW, LOOP_START},
                {ossim::nitf::SAMPLE_DIMENSION_KW, LOOP_START},
                    {ossim::nitf::URR_KW, 21, SCIENTIFIC},
                    {ossim::nitf::URC_KW, 21, SCIENTIFIC},
                    {ossim::nitf::UCC_KW, 21, SCIENTIFIC},
                {ossim::nitf::SAMPLE_DIMENSION_KW, LOOP_END},
            {ossim::nitf::SAMPLE_DIMENSION_KW, LOOP_END},
            {ossim::nitf::LINE_SPDCF_KW, 2, U_INT, 0, "1"},
            {ossim::nitf::SAMPLE_SPDCF_KW, 2, U_INT, 0, "2"},
        {ossim::nitf::UE_FLAG_KW + " = 1", IF_STATEMENT_END},
        {ossim::nitf::SPDCF_FLAG_KW, 1, U_INT, 0, "1"},
        {ossim::nitf::SPDCF_FLAG_KW + " = 1", IF_STATEMENT_START},
            {ossim::nitf::NUM_SPDCF_KW, 2, U_INT, 0, "8"},
            {ossim::nitf::NUM_SPDCF_KW, LOOP_START},
                {ossim::nitf::SPDCF_ID_KW, 2, U_INT},
                {ossim::nitf::SPDCF_P_KW, 2, U_INT, 0, "1"},
                {ossim::nitf::SPDCF_P_KW, LOOP_START},
                    {ossim::nitf::SPDCF_FAM_KW, 1, INT},
                    {ossim::nitf::SPDCF_WEIGHT_KW, 5, U_DOUBLE, 3, "1"},
                    {ossim::nitf::SPDCF_FAM_KW + " = 0", IF_STATEMENT_START},
                        {ossim::nitf::FP_A_KW, 8, U_DOUBLE, 6, "1"},
                        {ossim::nitf::FP_ALPHA_KW, 8, U_DOUBLE, 6, ".1"},
                        {ossim::nitf::FP_BETA_KW, 9, U_DOUBLE, 6, "10"},
                        {ossim::nitf::FP_T_KW, 21, SCIENTIFIC},
                    {ossim::nitf::SPDCF_FAM_KW + " = 0", IF_STATEMENT_END},
                    {ossim::nitf::SPDCF_FAM_KW + " = 1", IF_STATEMENT_START},
                        {ossim::nitf::NUM_SEGS_KW, 2, U_INT},
                        {ossim::nitf::NUM_SEGS_KW, LOOP_START},
                            {ossim::nitf::PL_MAX_COR_KW, 8, U_DOUBLE, 6},
                            {ossim::nitf::PL_TAU_MAX_COR_KW, 21, SCIENTIFIC},
                        {ossim::nitf::NUM_SEGS_KW, LOOP_END},
                    {ossim::nitf::SPDCF_FAM_KW + " = 1", IF_STATEMENT_END},
                    {ossim::nitf::SPDCF_FAM_KW + " = 2", IF_STATEMENT_START},
                        {ossim::nitf::DC_A_KW, 8, U_DOUBLE, 6},
                        {ossim::nitf::DC_T_KW, 21, SCIENTIFIC},
                        {ossim::nitf::DC_P_KW, 21, SCIENTIFIC},
                    {ossim::nitf::SPDCF_FAM_KW + " = 2", IF_STATEMENT_END},
                {ossim::nitf::SPDCF_P_KW, LOOP_END},
            {ossim::nitf::SPDCF_P_KW, LOOP_END},
        {ossim::nitf::SPDCF_FLAG_KW + " = 1", IF_STATEMENT_END},
        {ossim::nitf::DIRECT_COVARIANCE_FLAG_KW, 1, U_INT},
        {ossim::nitf::DIRECT_COVARIANCE_FLAG_KW + " = 1", IF_STATEMENT_START},
            {ossim::nitf::DC_TYPE_KW, 1, SCIENTIFIC},
            {ossim::nitf::DC_TYPE_KW + " = 0", IF_STATEMENT_START},
                {ossim::nitf::NUM_PARA_KW, 4, U_INT},
                {ossim::nitf::NUM_PARA_KW, LOOP_START},
                    {ossim::nitf::ADJ_KW, 21, SCIENTIFIC},
                {ossim::nitf::NUM_PARA_KW, LOOP_END},
                {"( " + ossim::nitf::NUM_PARA_KW + " * 0.5 ) * ( " + ossim::nitf::NUM_PARA_KW + " + 1 )", LOOP_START},
                    {ossim::nitf::ERRCOV_C4_KW, 21, SCIENTIFIC},
                {"( " + ossim::nitf::NUM_PARA_KW + " * 0.5 ) * ( " + ossim::nitf::NUM_PARA_KW + " + 1 )", LOOP_END},
            {ossim::nitf::DC_TYPE_KW + " = 0", IF_STATEMENT_END},
        {ossim::nitf::DIRECT_COVARIANCE_FLAG_KW + " = 1", IF_STATEMENT_END},
        {ossim::nitf::RESERVED_LEN_KW, 9, U_INT},
        {"! ( " + ossim::nitf::RESERVED_LEN_KW + " = 0  )", IF_STATEMENT_START},
            {ossim::nitf::MASK_LEN_KW, 2, U_INT},
            {ossim::nitf::RESERVED_FIELD_MASK_KW + " " + ossim::nitf::MASK_LEN_KW, VARIABLE_LENGTH, U_INT},
            {ossim::nitf::RESERVED_FIELD_MASK_KW + "[0] = 1", IF_STATEMENT_START},
                {ossim::nitf::RESERVED_LEN_AREA1_KW, 9, SCIENTIFIC},
                {ossim::nitf::NUM_PARA_KW, LOOP_START},
                    {ossim::nitf::SPDCF_ID_ADJ_KW, 2, U_INT},
                {ossim::nitf::NUM_PARA_KW, LOOP_END},
        {"! ( " + ossim::nitf::RESERVED_LEN_KW + " = 0  )", IF_STATEMENT_END},
   	/* Unused future reserved area
  		{"Start of the future Reserved Field Areas loop. Loop runs from i = 2 to MASK_LEN when MASK_LEN is > 1.", LOOP_START},
  			{"If character i in RESERVED_FIELD_MASK is 1. A type of 'Ri' is used to denote fields that are required when Reserved Area i is present.", IF_STATEMENT_START},
  				{"RESERVED_LEN_AREAi", "9", U_DOUBLE, 0},
  				{"Start of bytes counted by RESERVED_LEN_AREAi.", LOOP_START},
  					{"RESERVED_AREAi", ""varies"", U_INT},
  				{"End of bytes counted by RESERVED_LEN_AREAi.", LOOP_END},
  			{"End if character i in RESERVED_FIELD_MASK is 1.", LOOP_END},
  		{"End of the future Reserved Field Areas loop.", LOOP_END},
  	*/
    {"End of Reserved Field Areas (bytes counted by RESERVED_LEN).", IF_STATEMENT_END}
	};
}

ossimString ossimNitfCscsdbDes::getClassName() const
{
   return ossimString("ossimNitfCscsdbdes");
}
