//----------------------------------------------------------------------------
//
// License:  MIT
//
// See LICENSE.txt file in the top level directory for more details.
//
// Author:  Ryan Feldbush
//
// Description: CSCSDB des class definition.
//
// Exploitation Reference Data TRE.
//
// See document App AH - GLAS-GFM table AH.6.6 for more info.
//
//----------------------------------------------------------------------------

#include <ossim/support_data/ossimNitfCscsdbDes.h>
#include <ossim/base/ossimNotify.h>
#include <ossim/base/ossimTrace.h>
#include <ossim/support_data/ossimNitfCommonFieldNames.h>

static ossimTrace traceDebug("ossimNitfCscsdbdes:debug");

const std::string ossimNitfCscsdbDes::CETAG_KW = "CSCSDB";

ossimNitfCscsdbDes::ossimNitfCscsdbDes()
   : ossimNitfGenericDes("CSCSDB")
{
	initializeFieldDefinitions();
	initializeFields();
	setDesSubHeaderLength(getDesSubHeaderLength());
	setDesDataLength(getDesDataLength());
}

ossimNitfCscsdbDes::ossimNitfCscsdbDes(ossim_uint32 tagLength)
   : ossimNitfGenericDes("CSCSDB", tagLength)
{
	initializeFieldDefinitions();
	initializeFields();
	setDesSubHeaderLength(getDesSubHeaderLength());
}
void ossimNitfCscsdbDes::initializeFieldDefinitions()
{
   FIELD_DEFINITIONS =
   {
   {"UUID", 36, 0, 0, " "},
	{"NUMAIS", 3, 0, 0, "ALL"},
	{"NUMAIS n", LOOP_START},
		{"AISDLVL", 3, 1},
	{"NUMAIS n", LOOP_END},
	{"NUM_ASSOC_ELEM", 3, 1, 0, "1"},
	{"NUM_ASSOC_ELEM n", LOOP_START},
		{"ASSOC_ELEM_UUID", 36, 0},
	{"NUM_ASSOC_ELEM n", LOOP_END},
	{"RESERVEDSUBH_LEN", 4, 1},
	{"RESERVEDSUBH RESERVEDSUBH_LEN", VARIABLE_LENGTH, 1},
  	{"COV_VERSION_DATE", 8, U_INT, 0, "20240501"},
  	{"CORE_SETS", 1, U_INT, 0, "1"},
	{"CORE_SETS n", LOOP_START},
		{"REF_FRAME_POSITION", 1, U_INT, 0, "1"},
		{"REF_FRAME_ATTITUDE", 1, U_INT, 0, "2"},
		{"NUM_GROUPS", 1, U_INT, 0, "4"},
		{"NUM_GROUPS j", LOOP_START},
  			{"CORR_REF_DATE", 8, U_INT, 0, "20000101"},
  			{"CORR_REF_TIME", 16, U_DOUBLE, 9},
  			{"NUM_ADJ_PARM", 1, U_INT},
			{"NUM_ADJ_PARM k", LOOP_START},
				{"ADJ_PARM_ID", 1, U_INT},
			{"NUM_ADJ_PARM k", LOOP_END},
			{"BASIC_SUB_ALLOC", 1, U_INT, 0, "1"},
  			{"BASIC_SUB_ALLOC 1 =", IF_STATEMENT_START},
  				{"NUM_ADJ_PARM 0.5 * NUM_ADJ_PARM 1 + * k", LOOP_START},
					{"ERRCOV_C1", 21, SCIENTIFIC, 0, "1.0e-16"},
  				{"NUM_ADJ_PARM 0.5 * NUM_ADJ_PARM 1 + * k", LOOP_END},
				{"BASIC_PF_FLAG", 1, U_INT},
  				{"BASIC_PF_FLAG 1 =", IF_STATEMENT_START},
					{"NUM_BASIC_PF", 2, U_INT},
  					{"NUM_BASIC_PF k", LOOP_START},
  						{"BASIC_PF_SPDCF", 2, U_INT},
  						{"NUM_PAIRINGS_BASIC_PF", 2, U_INT},
  						{"NUM_PAIRINGS_BASIC_PF p", LOOP_START},
  							{"BASIC_PF_SPDCF_SENSOR", 6, ASCII},
  						{"NUM_PAIRINGS_BASIC_PF p", LOOP_END},
  					{"NUM_BASIC_PF k", LOOP_END},
  				{"BASIC_PF_FLAG 1 =", IF_STATEMENT_END},
  				{"BASIC_PL_FLAG", 1, U_INT},
  				{"BASIC_PL_FLAG 1 =", IF_STATEMENT_START},
  					{"NUM_BASIC_PL", 2, U_INT},
  					{"NUM_BASIC_PL k", LOOP_START},
  						{"BASIC_PL_SPDCF", 2, U_INT},
  						{"NUM_PAIRINGS_BASIC_PL", 2, U_INT},
  						{"NUM_PAIRINGS_BASIC_PL p", LOOP_START},
  							{"BASIC_PL_SPDCF_SENSOR", 6, ASCII},
  						{"NUM_PAIRINGS_BASIC_PL p", LOOP_END},
  					{"NUM_BASIC_PL k", LOOP_END},
  				{"BASIC_PL_FLAG 1 =", IF_STATEMENT_END},
				{"BASIC_SR_FLAG", 1, U_INT, 0, "1"},
  				{"BASIC_SR_FLAG 1 =", IF_STATEMENT_START},
  					{"BASIC_SR_SPDCF", 2, U_INT},
  				{"BASIC_SR_FLAG 1 =", IF_STATEMENT_END},
			{"BASIC_SUB_ALLOC 1 =", IF_STATEMENT_END},
  			{"POST_SUB_ALLOC", 1, U_INT, 0, "1"},
  			{"POST_SUB_ALLOC 1 =", IF_STATEMENT_START},
  				{"POST_START_DATE", 8, U_INT},
  				{"POST_START_TIME", 15, U_DOUBLE, 9},
  				{"POST_DT", 13, U_DOUBLE, 9},
  				{"NUM_POSTS", 3, U_INT},
  				{"COMMON_POSTS_COV", 1, U_INT, 0, "1"},
  				{"COMMON_POSTS_COV 1 =", IF_STATEMENT_START},
  					{"NUM_ADJ_PARM 0.5 * NUM_ADJ_PARM 1 + * k", LOOP_START},
  						{"ERRCOV_C2", 21, SCIENTIFIC},
  					{"NUM_ADJ_PARM 0.5 * NUM_ADJ_PARM 1 + * k", LOOP_END},
  				{"COMMON_POSTS_COV 1 =", IF_STATEMENT_END},
  				{"COMMON_POSTS_COV 0 =", IF_STATEMENT_START},
  					{"NUM_POSTS k", LOOP_START},
  						{"NUM_ADJ_PARM 0.5 * NUM_ADJ_PARM 1 + * p", LOOP_START},
  							{"ERRCOV_C2", 21, SCIENTIFIC},
  						{"NUM_ADJ_PARM 0.5 * NUM_ADJ_PARM 1 + * p", LOOP_END},
  					{"NUM_POSTS k", LOOP_END},
  				{"COMMON_POSTS_COV 0 =", IF_STATEMENT_END},
  				{"POST_INTERP", 1, U_INT, 0, "1"},
  				{"POST_PF_FLAG", 1, U_INT},
  				{"POST_PF_FLAG 1 =", IF_STATEMENT_START},
  					{"NUM_POST_PF", 2, U_INT},
  					{"NUM_POST_PF k", LOOP_START},
  						{"POST_PF_SPDCF", 2, U_INT},
  						{"NUM_PAIRINGS_POST_PF", 2, U_INT},
  						{"NUM_PAIRINGS_POST_PF p", LOOP_START},
  							{"POST_PF_SPDCF_SENSOR", 6, SCIENTIFIC},
  						{"NUM_PAIRINGS_POST_PF p", LOOP_END},
  					{"NUM_POST_PF k", LOOP_END},
  				{"POST_PF_FLAG 1 =", IF_STATEMENT_END},
  				{"POST_PL_FLAG", 1, U_INT},
  				{"POST_PL_FLAG 1 =", IF_STATEMENT_START},
  					{"NUM_POST_PL", 2, U_INT},
  					{"NUM_POST_PL k", LOOP_START},
  						{"POST_PL_SPDCF", 2, U_INT},
  						{"NUM_PAIRINGS_POST_PL", 2, U_INT},
  						{"NUM_PAIRINGS_POST_PL p", LOOP_START},
  							{"POST_PL_SPDCF_SENSOR", 6, ASCII},
  						{"NUM_PAIRINGS_POST_PL p", LOOP_END},
  					{"NUM_POST_PL k", LOOP_END},
  				{"POST_PL_FLAG 1 =", IF_STATEMENT_END},
				{"POST_SR_FLAG", 1, U_INT, 0, "1"},
  				{"POST_SR_FLAG 1 =", IF_STATEMENT_START},
  					{"POST_SR_SPDCF", 2, U_INT},
  					{"POST_CORR", 1, U_INT},
  				{"POST_SR_FLAG 1 =", IF_STATEMENT_END},
			{"POST_SUB_ALLOC 1 =", IF_STATEMENT_END},
  		{"NUM_GROUPS j", LOOP_END},
  	{"ECORE_SETS n", LOOP_END},
  	{"IO_CAL_AP", 1, U_INT},
  	{"IO_CAL_AP 1 =", IF_STATEMENT_START},
  		{"NUM_SETS_CAL_AP", 2, U_INT},
  		{"NUM_SETS_CAL_AP n", LOOP_START},
  			{"FOCAL_LENGTH_CAL", 11, U_DOUBLE, 8},
  		{"NUM_SETS_CAL_AP n", LOOP_END},
  		{"NCAL_CPG", 2, U_INT},
  		{"NCAL_CPG n", LOOP_START},
  			{"CORR_REF_DATE_IO", 8, U_INT},
  			{"CORR_REF_TIME_IO", 16, U_DOUBLE, 9},
  			{"N1CAL", 2, U_INT},
  			{"N1CAL j", LOOP_START},
  				{"CAL_AP_ID", 2, U_INT},
  			{"N1CAL j", LOOP_END},
  			{"NUM_SETS_CAL_AP j", LOOP_START},
  				{"N1CAL 0.5 * N1CAL 1 + * k", LOOP_START},
  					{"ERRCOV_C3", 21, SCIENTIFIC},
  				{"N1CAL 0.5 * N1CAL 1 + * k", LOOP_END},
  			{"NUM_SETS_CAL_AP j", LOOP_END},
  			{"CAL_INTERP", 1, U_INT},
  			{"SPDCF_ID_TIME", 2, U_INT},
  			{"SPDCF_ID_FL", 2, U_INT},
  		{"NCAL_CPG n", LOOP_END},
  	{"IO_CAL_AP 1 =", IF_STATEMENT_END},
  	{"TS_CAL_AP", 1, U_INT},
  	{"TS_CAL_AP 1 =", IF_STATEMENT_START},
  		{"NUM_TS_GRP", 1, U_INT},
  		{"NUM_TS_GRP 1 =", IF_STATEMENT_START},
  			{"CORR_REF_DATE_TS", 8, U_INT},
  			{"CORR_REF_TIME_TS", 16, U_DOUBLE, 9},
  			{"TSRR", 21, SCIENTIFIC},
  			{"TSRC", 21, SCIENTIFIC},
  			{"TSCC", 21, SCIENTIFIC},
  			{"TS_SPDCF", 2, U_INT},
  		{"NUM_TS_GRP 1 =", IF_STATEMENT_END},
  		{"NUM_TS_GRP 2 =", IF_STATEMENT_START},
  			{"CORR_REF_DATE_TSP", 8, U_DOUBLE, 25},
  			{"CORR_REF_TIME_TSP", 16, U_DOUBLE, 25},
  			{"TS_POS_COV", 21, SCIENTIFIC},
  			{"TS_POS_SPDCF", 2, U_INT},
  			{"CORR_REF_DATE_TSA", 8, U_DOUBLE, 25},
  			{"CORR_REF_TIME_TSA", 16, U_DOUBLE, 25},
  			{"TS_ATT_COV", 21, SCIENTIFIC},
  			{"TS_ATT_SPDCF", 2, U_INT},
  		{"NUM_TS_GRP 2 =", IF_STATEMENT_END},
  		{"NUM_TS_GRP = 3", IF_STATEMENT_START},
  			{"CORR_REF_DATE_TS", 8, U_DOUBLE, 25},
  			{"CORR_REF_TIME_TS", 16, U_DOUBLE, 25},
  			{"TS_POS_COV", 21, SCIENTIFIC},
  			{"TS_POS_ATT_COV", 21, SCIENTIFIC},
  			{"TS_POS_FL_COV", 21, SCIENTIFIC},
  			{"TS_ATT_COV", 21, SCIENTIFIC},
  			{"TS_ATT_FL_COV", 21, SCIENTIFIC},
  			{"TS_FL_COV", 21, SCIENTIFIC},
  			{"TS_SPDCF", 2, U_INT},
  		{"NUM_TS_GRP = 3", IF_STATEMENT_END},
  		{"NUM_TS_GRP = 4", IF_STATEMENT_START},
  			{"CORR_REF_DATE_TSPA", 8, U_DOUBLE, 25},
  			{"CORR_REF_TIME_TSPA", 16, U_DOUBLE, 25},
  			{"TS_POS_COV", 21, SCIENTIFIC},
  			{"TS_POS_ATT_COV", 21, SCIENTIFIC},
  			{"TS_ATT_COV", 21, SCIENTIFIC},
  			{"TS_PA_SPDCF", 2, U_INT},
  			{"CORR_REF_DATE_TSFL", 8, U_DOUBLE, 25},
  			{"CORR_REF_TIME_TSFL", 16, U_DOUBLE, 25},
  			{"TS_FL_COV", 21, SCIENTIFIC},
  			{"TS_FL_SPDCF", 2, U_INT},
  		{"NUM_TS_GRP = 4", IF_STATEMENT_END},
  		{"NUM_TS_GRP = 5", IF_STATEMENT_START},
  			{"CORR_REF_DATE_TSP", 8, U_DOUBLE, 25},
  			{"CORR_REF_TIME_TSP", 16, U_DOUBLE, 25},
  			{"TS_POS_COV", 21, SCIENTIFIC},
  			{"TS_POS_SPDCF", 2, U_INT},
  			{"CORR_REF_DATE_TSA", 8, U_DOUBLE, 25},
  			{"CORR_REF_TIME_TSA", 16, U_DOUBLE, 25},
  			{"TS_ATT_COV", 21, SCIENTIFIC},
  			{"TS_ATT_SPDCF", 2, U_INT},
  			{"CORR_REF_DATE_TSFL", 8, U_DOUBLE, 25},
  			{"CORR_REF_TIME_TSFL", 16, U_DOUBLE, 25},
  			{"TS_FL_COV", 21, SCIENTIFIC},
  			{"TS_FL_SPDCF", 2, U_INT},
  		{"NUM_TS_GRP = 5", IF_STATEMENT_END},
  	{"TS_CAL_AP 1 =", IF_STATEMENT_END},
  	{"UE_FLAG", 1, U_INT, 0, "1"},
  	{"UE_FLAG 1 =", IF_STATEMENT_START},
  		{"LINE_DIMENSION", 3, U_INT},
  		{"SAMPLE_DIMENSION", 2, U_INT},
  		{"LINE_DIMENSION n", LOOP_START},
  			{"SAMPLE_DIMENSION j", LOOP_START},
  				{"URR", 21, SCIENTIFIC},
  				{"URC", 21, SCIENTIFIC},
  				{"UCC", 21, SCIENTIFIC},
  			{"SAMPLE_DIMENSION j", LOOP_END},
  		{"SAMPLE_DIMENSION j", LOOP_END},
  		{"LINE_SPDCF", 2, U_INT, 0, "1"},
  		{"SAMPLE_SPDCF", 2, U_INT, 0, "2"},
  	{"UE_FLAG 1 =", IF_STATEMENT_END},
  	{"SPDCF_FLAG", 1, U_INT, 0, "1"},
  	{"SPDCF_FLAG 1 =", IF_STATEMENT_START},
  		{"NUM_SPDCF", 2, U_INT, 0, "8"},
  		{"NUM_SPDCF n", LOOP_START},
  			{"SPDCF_ID", 2, U_INT},
  			{"SPDCF_P", 2, U_INT, 0, "1"},
  			{"SPDCF_P j", LOOP_START},
  				{"SPDCF_FAM", 1, INT},
  				{"SPDCF_WEIGHT", 5, U_DOUBLE, 3, "1"},
  				{"SPDCF_FAM 0 =", IF_STATEMENT_START},
  					{"FP_A", 8, U_DOUBLE, 6, "1"},
  					{"FP_ALPHA", 8, U_DOUBLE, 6, ".1"},
  					{"FP_BETA", 9, U_DOUBLE, 6, "10"},
  					{"FP_T", 21, SCIENTIFIC},
  				{"SPDCF_FAM 0 =", IF_STATEMENT_END},
  				{"SPDCF_FAM 1 =", IF_STATEMENT_START},
  					{"NUM_SEGS", 2, U_INT},
  					{"NUM_SEGS k", LOOP_START},
  						{"PL_MAX_COR", 8, U_DOUBLE, 6},
  						{"PL_TAU_MAX_COR", 21, SCIENTIFIC},
  					{"NUM_SEGS k", LOOP_END},
  				{"SPDCF_FAM 1 =", IF_STATEMENT_END},
  				{"SPDCF_FAM 2 =", IF_STATEMENT_START},
  					{"DC_A", 8, U_DOUBLE, 6},
  					{"DC_T", 21, SCIENTIFIC},
  					{"DC_P", 21, SCIENTIFIC},
  				{"SPDCF_FAM 2 =", IF_STATEMENT_END},
  			{"SPDCF_P j", LOOP_END},
  		{"SPDCF_P j", LOOP_END},
  	{"SPDCF_FLAG 1 =", IF_STATEMENT_END},
  	{"DIRECT_COVARIANCE_FLAG", 1, U_INT},
  	{"DIRECT_COVARIANCE_FLAG 1 =", IF_STATEMENT_START},
  		{"DC_TYPE", 1, SCIENTIFIC},
  		{"DC_TYPE 0 =", IF_STATEMENT_START},
  			{"NUM_PARA", 4, U_INT},
  			{"NUM_PARA n", LOOP_START},
  				{"ADJ", 21, SCIENTIFIC},
  			{"NUM_PARA n", LOOP_END},
  			{"NUM_PARA 0.5 * NUM_PARA 1 + * p", LOOP_START},
  				{"ERRCOV_C4", 21, SCIENTIFIC},
  			{"NUM_PARA 0.5 * NUM_PARA 1 + * p", LOOP_END},
  		{"DC_TYPE 0 =", IF_STATEMENT_END},
  	{"DIRECT_COVARIANCE_FLAG 1 =", IF_STATEMENT_END},
  	{"RESERVED_LEN", 9, U_INT},
  	{"RESERVED_LEN 0 = !", IF_STATEMENT_START},
  		{"MASK_LEN", 2, U_INT},
  		{"RESERVED_FIELD_MASK MASK_LEN", VARIABLE_LENGTH, U_INT},
  		{"RESERVED_FIELD_MASK[0] 1 =", IF_STATEMENT_START},
  			{"RESERVED_LEN_AREA1", 9, SCIENTIFIC},
  			{"NUM_PARA n", LOOP_START},
  				{"SPDCF_ID_ADJ", 2, U_INT},
  			{"NUM_PARA n", LOOP_END},
		{"End of Reserved Field Area 1.", IF_STATEMENT_END},
   	/* Unused future reserved area
  		{"Start of the future Reserved Field Areas loop. Loop runs from i = 2 to MASK_LEN when MASK_LEN is > 1.", LOOP_START},
  			{"If character i in RESERVED_FIELD_MASK is 1. A type of 'Ri' is used to denote fields that are required when Reserved Area i is present.", IF_STATEMENT_START},
  				{"RESERVED_LEN_AREAi", "9", U_DOUBLE, 0},
  				{"Start of bytes counted by RESERVED_LEN_AREAi.", LOOP_START},
  					{"RESERVED_AREAi", ""varies"", U_INT},
  				{"End of bytes counted by RESERVED_LEN_AREAi.", LOOP_END},
  			{"End if character i in RESERVED_FIELD_MASK is 1.", LOOP_END},
  		{"End of the future Reserved Field Areas loop.", LOOP_END},
  	*/
  	{"End of Reserved Field Areas (bytes counted by RESERVED_LEN).", IF_STATEMENT_END},
	};
}

ossimString ossimNitfCscsdbDes::getClassName() const
{
   return ossimString("ossimNitfCscsdbdes");
}
